#SIMULATION SETTINGS
PosX: -1482.767  #starting position
PosY: -1477.964

#feather boost in square mode - numbers can be seen in studio when boost is performed
#if both are 0, the GA will optimize the first frame without square gate
BoostX: 0  # - left | + right
BoostY: 0  # - up | + down

#frame number of angle inputs
Framecount: 120

SpinnerFile: DIRECTORY HERE #export using CelesteTAS feature (if none put "")
Killboxes: ""

Favorite: "
  15,F,270
  35,F,0
 100,F,90" 



#GENETIC SETTINGS
Population: 50
Generations: 800
SurvivorCount: 10
#probabilities are relative to their sum, only the ratio between them matters.
CrossoverProbability: 1
MutationProbability: 2
SimplificationProbability: 1



#FITNESS SETTINGS
Goal: x  # x | y | -x | -y | radial
#negative x/y means leftward/upward

#for x/y
SecMin: 1556  #goal position on secondary axis
SecMax: 1560
SecFactor: 10  #how many px on primary axis is 1px in secondary axis worth?

#for radial - goal position
GoalX: 0.0
GoalY: 0.0