#SIMULATION SETTINGS
pos_x: 7165.795268267390  #starting position
pos_y: 4475.500048935410

#feather boost in square mode - numbers can be seen in studio when boost is performed
#if both are 0, the GA will optimize the first frame without square gate
boost_x: 1.0  # - left | + right
boost_y: -1.0  # - up | + down

#frame number of angle inputs
dna_length: 100

spinner_file: ""  #export using CelesteTAS feature (if none put "")
spinners: "
7304,4448
"
killboxes: "

"

favorite: "
  43,F,83.12
  57,F,89.7
"



#GENETIC SETTINGS
population: 50
generations: 5000
crossover_probability: 0.8
mutation_probability: 0.2
elitism: 1



#FITNESS SETTINGS
goal: x  # x | y | radial

#for x/y
prim_dir: 1  #primary axis: 1 right/down | 0 left/up
sec_min: 4444.4999  #goal position on secondary axis
sec_max: 4000
sec_factor: 500.0  #how many px on primary axis is 1px in secondary axis worth?

#for radial - goal position
goal_x: 0.0
goal_y: 0.0
