spinner_file: C:\Users\Kilian\Programm\Celeste\TAS Files\test.tas

favorite: "
  10,F,27.1
  74,F,98
"

dna_length: 84

population: 20
elite: 5

mutation_strength: 5

goal: x # x | y | radial

#axis
prim_dir: 1  #main axis optimization: 1 right/down | 0 left/up
sec_min: -540.5  #goal position on secondary axis
sec_max: -530.5
sec_factor: 500.0  #how many px on main axis is 1px in secondary axis worth?

#radial - goal point
goal_x: 0.0
goal_y: 0.0

