#Warning! The file will be overwritten!
tas_file: C:\Users\Kilian\Programm\Celeste\TAS Files\test.tas

console_load: "
console load StrawberryJam2021/1-Beginner/1-Eclipse 79.999997735024 -469.583452701569 0 -240
"

header: "
  37
  11,U,Z
  26
"

favorite: "
  10,F,27.1
  74,F,98
"

dna_length: 84

population: 20
elite: 5

mutation_strength: 5

axis: x # x | y | radial

#x/y
prim_dir: + #main axis optimization: + right/down | - left/up
sec_min: -540.5 #goal position on secondary axis
sec_max: -530.5
sec_factor: 500.0 #how many px on main axis is 1px in secondary axis worth?

#radial - goal point
goal_x: 0.0
goal_y: 0.0





tas_wait: 1.5